-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
    decoration = {
        blur = {
            passes = 4,
            size = 8,
        },
    },
    misc = {
        disable_hyprland_logo = true,
    },
})
